# Generated by Django 5.2.3 on 2025-06-20 22:21

import django.db.models.deletion
import djmypypi2.models
import djmypypi2.uids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djmypypi2', '0002_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=djmypypi2.uids.get_uid, editable=False, max_length=40, unique=True, verbose_name='UID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('token', models.CharField(default=djmypypi2.models.generate_token, editable=False, max_length=100, unique=True, verbose_name='Token')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
            },
        ),
    ]
