# Generated by Django 5.2.3 on 2025-06-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djmypypi2', '0003_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='md5_digest',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='MD5'),
        ),
    ]
